version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=theosDB
    networks:
      - theos_network

  api:
    build:
      context: .
    image: theos_api
    container_name: api_node
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/theosDB
    networks:
      - theos_network

volumes:
  mongo_data:

networks:
  theos_network:
    driver: bridge
    name: theos_network
